name: workflow-dispatch-inputs
on:
  workflow_dispatch:
    inputs:
      input-num-1:
        description: 'first-num'
        required: true
      
        
      
      input-num-2:
        description: 'second-num'
        required: true
        
        
        
  #push:
   # branches:
    #- main
   

  #pull_request:
    #branches:
    #- main  
#env:
  #file: python.py 
  #first_num_1: ${{ github.event.inputs.input-num-1 }}
  #first_num_2: ${{ github.event.inputs.input-num-2 }}
  
jobs:
  check-python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.7'
      - name: python version
        run: python --version

    
      - name: python script
        run: |
          
          python python.py  ${{ github.event.inputs.input-num-1 }} ${{ github.event.inputs.input-num-2 }}
          python Document.py  ${{ github.event.inputs.input-num-1 }} ${{ github.event.inputs.input-num-2 }}
          
      
      
      
    
          
          
     
